[package]
name = "verify-torrent"
version = "0.1.0"
authors = ["tolien <tolien@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_bencode = "0.2.2"
clap = "2.33.3"
base64 = "0.12.3"
