[package]
name = "verify-torrent"
version = "0.1.0"
authors = ["tolien <tolien@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_bencode = "0.2.3"
clap = "3.0.1"
serde_derive = "1.0.132"
serde_bytes = "0.11.5"
serde = "1.0.132"
sha1 = "0.6.0"
tokio = { version = "1.15.0", features = ["full"] }
log4rs = "1.0.0"
log = "0.4.14"

[profile.dev]
split-debuginfo = "unpacked"
