[package]
name = "verify-torrent"
version = "0.1.0"
authors = ["tolien <tolien@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_bencode = "0.2.3"
clap = "3.2.22"
serde_derive = "1.0.140"
serde_bytes = "0.11.6"
serde = "1.0.145"
sha1 = "0.10.1"
tokio = { version = "1.20.1", features = ["full"] }
log4rs = "1.1.1"
log = "0.4.17"
base64ct = { version = "1.5.2", features = ["alloc"] }

[profile.dev]
split-debuginfo = "unpacked"
